In [2]:
pip install ucimlrepo

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy.matlib
import math
import signal
from ucimlrepo import fetch_ucirepo
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from scipy.spatial.distance import euclidean
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy.stats import multivariate_normal
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_iris
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, Normalizer
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.feature_selection import mutual_info_classif
from scipy.spatial import distance
from scipy.spatial.distance import cdist
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score

In [18]:
iris = load_iris()
X = iris.data
y = iris.target

Método da resubstituição

In [19]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [20]:
clf=MLPClassifier(hidden_layer_sizes=(100),activation='tanh', random_state=10, max_iter=40000).fit(X, y)
y_pred = clf.predict(X)
Perro = 1-accuracy_score(y, y_pred)
print("Prob de Erro:", Perro)
print(confusion_matrix(y, y_pred))

Prob de Erro: 0.020000000000000018
[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]


Calculando a variância da estimativa assumindo as classes equiprováveis

In [22]:
varP=(1/3)**2*2/50*(1-2/50)/50+(1/3)**2*1/50*(1-1/50)/50
stdP=np.sqrt(varP)
print('Estimativa desvio padrão do P',stdP)

Estimativa desvio padrão do P 0.011352924243950934


Método do holdout

In [23]:
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [24]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
clf=MLPClassifier(hidden_layer_sizes=(100),activation='tanh', random_state=10, max_iter=40000).fit(X_train, y_train)
y_pred = clf.predict(X_test)
Perro = 1-accuracy_score(y_test, y_pred)
print("Prob de Erro:", Perro)
print(confusion_matrix(y_test, y_pred))

Prob de Erro: 0.022222222222222254
[[13  0  0]
 [ 0 18  1]
 [ 0  0 13]]


In [30]:
varP=(1/3)**2*1/19*(1-1/19)/1
stdP=np.sqrt(varP)
print('Estimativa desvio padrão do P',stdP)

Estimativa desvio padrão do P 0.07443229275647868


Método leave-one-out

In [13]:
iris = load_iris()
X = iris.data
y = iris.target

In [14]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
erros=np.zeros(len(X))
aux=0
for i in range(len(X)):
    X_train=np.delete(X,i,0)
    y_train=np.delete(y,i)
    X_test=X[i]
    y_test=y[i]
    scaler = MinMaxScaler()
    clf=MLPClassifier(hidden_layer_sizes=(100,),activation='tanh', random_state=10, max_iter=40000).fit(X_train, y_train)
    y_pred = clf.predict(X_test.reshape(1, -1))
    if y_pred!=y_test:
      aux=aux+1;
      erros[i]=i;

In [15]:
Perro = aux/len(X)
print("Prob de Erro:", Perro)

Prob de Erro: 0.03333333333333333


In [16]:
erros

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,  68.,   0.,  70.,   0.,   0.,   0.,   0.,   0.,   0.,
        77.,   0.,   0.,   0.,   0.,   0.,  83.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0., 133.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [17]:
Conf=np.matrix([[50, 0, 0],
               [0, 46, 4],
               [0, 1, 49]])

In [18]:
print(Conf)

[[50  0  0]
 [ 0 46  4]
 [ 0  1 49]]


In [19]:
varP=(1/3)**2*4/50*(1-4/50)/50+(1/3)**2*1/50*(1-1/50)/50
stdP=np.sqrt(varP)
print('Estimativa desvio padrão do P',stdP)

Estimativa desvio padrão do P 0.014391355429948603


Validação cruzada

In [21]:
iris = load_iris()
X = iris.data
y = iris.target

In [22]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [23]:
clf=MLPClassifier(hidden_layer_sizes=(100),activation='tanh', random_state=10, max_iter=40000)
scores = cross_val_score(clf, X, y, cv=5)
Perro=1-scores
print(Perro)
print(np.mean(Perro))
print(np.std(Perro))

[0.         0.         0.06666667 0.06666667 0.        ]
0.02666666666666666
0.03265986323710904
